### ISSUE TITLE
Class menu broken

### ISSUE THREAD

**Issue by Proluiz** [PlusGit/theta#12]
are broken in some way, ever rejoining wont fix.

**Comment by Proluiz** [comment]
Still broken

**Comment by Proluiz** [comment]
This information is not to fix ll but help bit: 
Try to apply a forced quit of menu if player spectate or join (why also on join? if a player disconnect with menu open the new player will take his slot and it may cause he get a broken menu), also apply it if player dies (i can still use the menu ever death).

**Comment by Proluiz** [comment]
Maybe is a user error map.

**Comment by PlusGit** [comment]
It appears some menu scripts were triggered with `ACS_Execute` and not `ACS_ExecuteAlways`.

68e7a50a78491f47c8e0d7a987808403425f84fa and 19d7716d312a5142392409016476a30a64cf70c4 should fix this.

**Comment by Proluiz** [comment]
also for future reference (tested in protox branch whitout your menu fix only to test).

<Protox>	since sean are afk
<Protox>	i have to test it whit you
<Protox>	but you know what happened
<Madcat>	just tell me what to do
<Protox>	by reading these lines
<Protox>	<Protox>	Script 10 is called by an "Actor Enters Sector" thing using ACS_ExecuteAlways. It sets a flag variable to true and loops until the flag is false. Script 11 is called by an "Actor Leaves Sector" thing, and unsets the flag variable. The flag system is necessary because the script cannot be ended simply by using ACS_Terminate on it.
<Protox>	<Protox>	Like ACS_Execute, this special starts a script. However, it will allow multiple instances of a script to run simultaneously. The downside is that any scripts started with this special cannot be suspended or terminated with ACS_Suspend or ACS_Terminate, respectively.
<Protox>	our version use acs execute
<Protox>	if someone is using menu
<Protox>	the 2nd player
<Protox>	cant use
<Madcat>	sorry, ACS is not my cup of tea
<Protox>	resulting in random frozens
<Protox>	but is easy to stand
<Protox>	2 players cant run menu in same time
<Protox>	remeneber you was using menu
<Protox>	i used and froze in me
<Protox>	so i do the revese
<Protox>	i used menu
<Protox>	and i told you to use and you crashed
<Protox>	simple :P

**Comment by Proluiz** [comment]
Finally fixed
