### ISSUE TITLE
Mechs get shrinked?

### ISSUE THREAD

**Issue by Proluiz** [PlusGit/theta#15]
Mechs looks much smaller than before, looks like a zandronum 2.1 bug too.

**Comment by PlusGit** [comment]
I think tuienie a Zandronum issue - there was a bug some time ago about skin scaling.

However, it should not be hard to use the `Svale` property on the mech actors.

**Comment by PlusGit** [comment]
Yeah, its a Zandronum bug. I'm really sure mexhs aren't the size of a normal player.

**Comment by Proluiz** [comment]
fixed removing the mech data from skininfo.
https://github.com/PlusGit/theta/commit/6874f9f22009f9b8a2d55e3641ff3fb8e44f597f
