### ISSUE TITLE
AOW04 has a bunch of missing textures.

### ISSUE THREAD

**Issue by PlusGit** [PlusGit/theta#16]
Possibly related to #5.

**Comment by Proluiz** [comment]
yes is related

**Comment by Proluiz** [comment]
aow04 is now unplayable sorry, maybe i'll return to a old version, apply the classic building layout and redo the map from omega aow.

**Comment by PlusGit** [comment]
Didn't I fix this?

**Comment by PlusGit** [comment]
I did: 9be982d21efe7c3bc05ccd0b953356fa6d2270a9
