### ISSUE TITLE
IsBlue/IsRed + Team Autobalance = issues

### ISSUE THREAD

**Issue by PlusGit** [PlusGit/theta#2]
Issue thread for discussing the `IsBlue`/`IsRed` and team autobalance issues.

**Comment by Proluiz** [comment]
invulnerable no, i know what happened, the auto balance of this version dont clear your inventory, so when you get caught by auto balance your inventory is keep like a iten called "isblue" and "isred" now lets talk about how obelisk work...

Oblisk is a monsters whit -Friend tag it mean he is aiming to everyone including his teammates but to prevent obelisk of do a rampage he check if the player has (if is tesla coil check if target) have inventory called "isred" if he have so shot, if it dont have look for other target until get someone but when you teamswitch you have bothinventorys so obelisk simple ignore you.

**Comment by PlusGit** [comment]
Weirdly, the player has IsBlue/IsRed set on team change.
https://github.com/PlusGit/theta/blob/master/src/code/acs_src/a_functions.acs#L707

**Comment by PlusGit** [comment]
This issue is not reproducible offline.

**Comment by Proluiz** [comment]
not happened anymore and i tested online

**Comment by Proluiz** [comment]
comes to happen again also i got some information how to reproduce:

Join any team, choose a class and tell to fried join on your team, i'll got switched and enemy obelisk wont target you.

Maybe is caused because on team switch the inventory isred/isblue is not TAKEN OUT.

**Comment by PlusGit** [comment]
It appears it still happens, and I've no idea why.

**Comment by PlusGit** [comment]
Seeing as the only workaround available to me at the moment is to kill the player after switching their teams, I might have to do that...

**Comment by PlusGit** [comment]
I think this is fixed. I tried to reproduce in two ways:
 1. adding a bot and joining the bot's team so I get teamswitched
 2. starting server, adding 2 clients and having them both join the same team so one gets teamswitched

and it did not occur.

**Comment by Proluiz** [comment]
still happens

**Comment by PlusGit** [comment]
![screenshot_doom_20151015_075940](https://cloud.githubusercontent.com/assets/2996684/10506731/c437babe-7312-11e5-92db-2da65e8480fb.png)
Think I found why.

**Comment by Proluiz** [comment]
nice, now the testing actors became usefull heh

**Comment by PlusGit** [comment]
Hmm. I was only able to reproduce this issue on only 4 maps:
 - `AOW01` Red Zone
 - `AOW04` Oasis
 - `AOW08` Valley
 - `AOW09` Infected

I'll take a look and see if there's anything map-specific about this...

**Comment by PlusGit** [comment]
Seems fixed everywhere but `AOW99`.. so I dunno.

**Comment by PlusGit** [comment]
Nope. Seems to happen randomly :/

**Comment by PlusGit** [comment]
A-HA! I found the issue.
When the player gets their team switched, they are respawned. This calls script 10 - which assumes the player's team is __always__ blue:
```
DEBUG | #0 | Seting amount of IsBlue to 0
DEBUG | #0 | Seting amount of IsRed to 1
DEBUG | #0 | Seting amount of TeamSwitchedRB to 0
DEBUG | #0 | Seting amount of TeamSwitchedBR to 1
DEBUG | #-1 | Seting amount of IsBlue to 1
DEBUG | #-1 | Seting amount of IsRed to 0
DEBUG | #-1 | Player respawned. Their team is Blue
DEBUG | #-1 | Seting amount of IsBlue to 1
DEBUG | #-1 | Seting amount of IsRed to 0
```
As you can see in the log above, I am being teamswitched to Red - but script 10 thinks otherwise.

**Comment by PlusGit** [comment]
Seems the server "player" tried to use `SetInventory`, which would set the inventory of the actual player.

**Comment by PlusGit** [comment]
Dunno. I think it happens somewhere in [script 10](https://github.com/PlusGit/theta/blob/master/src/code/acs_src/a_core.acs#L224-L249) -- but I've no fucking idea.

**Comment by Proluiz** [comment]
fixed

**Comment by PlusGit** [comment]
We'd still better watch out for this, though!
