### ISSUE TITLE
Autobalance weapon color poblems.

### ISSUE THREAD

**Issue by Proluiz** [PlusGit/theta#33]
For some reason color based guns (rocket launcher, plasma cannon and etc) get your color changed by team balance, looks like something related to isblue/isred.

**Comment by PlusGit** [comment]
They do or don't?

**Comment by Proluiz** [comment]
impossible to test, since menu is not letting i choose a class in normal way.

**Comment by PlusGit** [comment]
I tested the Plasma Gun, Rocket Launcher, and Plasma Cannon, and they all worked as expected when I got teamswitched by autobalance.

**Comment by PlusGit** [comment]
This is because of #2 - closing.
