### ISSUE TITLE
Better versioning system

### ISSUE THREAD

**Issue by PlusGit** [PlusGit/theta#36]
Currently, our versioning system of `YYMMDD` isn't very good. I think we need something better.

I propose 2 ideas:

1. __GNOME-like versioning__  
   The GNOME desktop environment's versioning system is like this:  
   `MAJOR.MINOR.PATCH`  
   The `MINOR` version increments with each version, but:
    - Odd `MINOR` versions are __beta__ releases (e.g. 3.17 is a beta for 3.18)
    - Even `MINOR` versions are __stable__ releases (e.g. 3.18)

2. __"Classic" versioning__
    This one's easy:  
    `MAJOR.MINOR`  
    Start at `1.0`.  
    Increment `MINOR` after every release.
    Append `-beta` etc. if it's a beta release (e.g. 1.2-beta)

I think GNOME-like versioning is a good way to go.

**Comment by Proluiz** [comment]
GNOME-like versioning

**Comment by PlusGit** [comment]
We've switched to GNOME-like versioning.
