### ISSUE TITLE
Client-Side menus not work Online

### ISSUE THREAD

**Issue by Proluiz** [PlusGit/theta#40]
For some reason the called script bug online due lack of imformation about clientside commands, also everything becomes a BIGFONT.

(server Data)
*** AOW02: Barrens ***

compatflags changed to: 0
Connect (v2.1.2): 192.168.0.3:10667
dmflags changed to: 1611153408
zacompatflags changed to: 131072
zacompatflags changed to: 131074
Protox has connected.
Protox joined the Red team.
Protox (#0, Red) becomes Gunman
Protox killed himself.
RequestScriptPuke: Attempted to call script 492 on the server. Only use RequestScriptPuke in CLIENTSIDE scripts.
RequestScriptPuke: Attempted to call script 484 on the server. Only use RequestScriptPuke in CLIENTSIDE scripts.
Protox (#0, Red) becomes Gunman
client Protox disconnected.
(End of file)

**Comment by PlusGit** [comment]
Is this for research or classes?

**Comment by Proluiz** [comment]
spawnroom classes, not tested res yet, since i'm unable to move.

**Comment by PlusGit** [comment]
#41.
