### ISSUE TITLE
possible version number on builder?

### ISSUE THREAD

**Issue by Proluiz** [PlusGit/theta#6]
I want a version number on builder to see, maybe you can set it on the final of build or in the begin and set the guy to press any key to continue.

**Comment by PlusGit** [comment]
Huh? Can you explain more clearly?

**Comment by PlusGit** [comment]
Do you want `build.bat` to display something like this when it's finished?

`Files are in: C:\Doom\theta\out\`

**Comment by Proluiz** [comment]
nope. i mean something on begin like this:

You're building version #########

**Comment by PlusGit** [comment]
Oh. I suppose I could use `git log` to do that.  
I'll take a look later.

**Comment by PlusGit** [comment]
Oh, right. Fixed this with the introduction of the `gitcommit` tool.
