### ISSUE TITLE
Autobalance is switching the wrong player

### ISSUE THREAD

**Issue by Proluiz** [PlusGit/theta#7]
Simple create a server, and do 2 clients, join one in red, go to other client and join red too, you'll see the client that was ALREADY in red team is being switched to blue.

**Comment by PlusGit** [comment]
How often does this occur? Test it a few times.

**Comment by Proluiz** [comment]
confirmed on 1st alpha test

**Comment by PlusGit** [comment]
I think my fix works. Needs continued testing.

**Comment by Proluiz** [comment]
still happening

**Comment by Proluiz** [comment]
labeled has bug since it is causing more critical glitchs, for example the glitchs: #19 and #10 maybe is caused by this error there.

**Comment by Proluiz** [comment]
this one is fixed but we have other now
