### ISSUE TITLE
Player colours are wrong.

### ISSUE THREAD

**Issue by Proluiz** [PlusGit/theta#8]
Most players are coloured incorrectly, most common colour is grey.
This also applies to AI marines.

**Comment by Proluiz** [comment]
![screenshot_doom_20150705_120424](https://cloud.githubusercontent.com/assets/6380147/8512199/88811d16-230e-11e5-94a7-702b94d4f92a.png)
![screenshot_doom_20150705_120602](https://cloud.githubusercontent.com/assets/6380147/8512200/88b65170-230e-11e5-8fa5-bcd3049149bd.png)

At least for the ais are all fine now.

**Comment by Proluiz** [comment]
How it are now.
![screenshot_doom_20150705_134826](https://cloud.githubusercontent.com/assets/6380147/8512552/70eba5b2-231e-11e5-9948-2dc2524fb373.png)
![screenshot_doom_20150705_135847](https://cloud.githubusercontent.com/assets/6380147/8512553/70ee70ee-231e-11e5-8d23-de776e031caf.png)

Ai still not follow the player color "PERFECTLY" but is alredy done.

Now they only need of a small touch up, chnged to improvement now

**Comment by PlusGit** [comment]
Much better!

**Comment by Proluiz** [comment]
Here more screen in-game:
![screenshot_doom_20150705_141110](https://cloud.githubusercontent.com/assets/6380147/8512592/e8073588-2320-11e5-9067-5798356dea7a.png)
![screenshot_doom_20150705_141129](https://cloud.githubusercontent.com/assets/6380147/8512595/e80d130e-2320-11e5-8b1e-a7ff15a34bde.png)
![screenshot_doom_20150705_141156](https://cloud.githubusercontent.com/assets/6380147/8512593/e8093bb2-2320-11e5-9978-b5502caa8943.png)
![screenshot_doom_20150705_141157](https://cloud.githubusercontent.com/assets/6380147/8512594/e80a7c3e-2320-11e5-98f5-37e83ec33c7f.png)
![screenshot_doom_20150705_141324](https://cloud.githubusercontent.com/assets/6380147/8512596/e80e7780-2320-11e5-8890-c6546f47c74b.png)
![screenshot_doom_20150705_141352](https://cloud.githubusercontent.com/assets/6380147/8512597/e8133716-2320-11e5-89bd-17b71a4393ec.png)
![screenshot_doom_20150705_141423](https://cloud.githubusercontent.com/assets/6380147/8512598/e8234660-2320-11e5-8552-891836b13370.png)
![screenshot_doom_20150705_141529](https://cloud.githubusercontent.com/assets/6380147/8512599/e82f1e86-2320-11e5-8d76-b5a9b69070e9.png)
![screenshot_doom_20150705_141605](https://cloud.githubusercontent.com/assets/6380147/8512600/e830e9fa-2320-11e5-823c-078ce7e692ac.png)
![screenshot_doom_20150705_141625](https://cloud.githubusercontent.com/assets/6380147/8512601/e8332986-2320-11e5-91d8-6b95092a2d0a.png)
![screenshot_doom_20150705_141734](https://cloud.githubusercontent.com/assets/6380147/8512602/e8362136-2320-11e5-8945-b90e7c9ed034.png)
![screenshot_doom_20150705_141001](https://cloud.githubusercontent.com/assets/6380147/8512603/e837789c-2320-11e5-909d-6292fdb6febc.png)

**Comment by PlusGit** [comment]
All looks good. Think we can close this?

**Comment by Proluiz** [comment]
ok if you want
